from django.conf import settings

def resource_urls(request):
    defaults = dict(
        #STATIC_URL=settings.STATIC_URL,
        SITE_NAME=settings.SITE_NAME,
        JAKSERVICE_IMPACT_CLASS_URL=settings.JAKSERVICE_IMPACT_CLASS_URL,
        JAKSERVICE_IMPACT_CLASS_FILENAME=settings.JAKSERVICE_IMPACT_CLASS_FILENAME,
        JAKSERVICE_AGGREGATE_URL=settings.JAKSERVICE_AGGREGATE_URL,
        JAKSERVICE_AGGREGATE_FILENAME=settings.JAKSERVICE_AGGREGATE_FILENAME,
        JAKSERVICE_ASSUMPTIONS_URL=settings.JAKSERVICE_ASSUMPTIONS_URL,
        JAKSERVICE_ASSUMPTIONS_DAMAGE_FILENAME=settings.JAKSERVICE_ASSUMPTIONS_DAMAGE_FILENAME,
        JAKSERVICE_ASSUMPTIONS_LOSS_FILENAME=settings.JAKSERVICE_ASSUMPTIONS_LOSS_FILENAME,
        JAKSERVICE_ASSUMPTIONS_AGGREGATE_FILENAME=settings.JAKSERVICE_ASSUMPTIONS_AGGREGATE_FILENAME,
        JAKSERVICE_ASSUMPTIONS_INSURANCE_FILENAME=settings.JAKSERVICE_ASSUMPTIONS_INSURANCE_FILENAME,
        JAKSERVICE_ASSUMPTIONS_INSURANCE_PENETRATION_FILENAME=settings.JAKSERVICE_ASSUMPTIONS_INSURANCE_PENETRATION_FILENAME,
    )
    
    return defaults